import { Preference, PreferenceType, AchievementType } from "./data.model";

export const PREFERENCES: Preference[] = [
  // Colors (Base Game)
  { id: "COLOR_RED", label: "Red", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },
  { id: "COLOR_ORANGE", label: "Orange", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },
  { id: "COLOR_YELLOW", label: "Yellow", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },
  { id: "COLOR_GREEN", label: "Green", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },
  { id: "COLOR_BLUE", label: "Blue", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },
  { id: "COLOR_PURPLE", label: "Purple", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },
  { id: "COLOR_PINK", label: "Pink", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },
  { id: "COLOR_BROWN", label: "Brown", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },
  { id: "COLOR_BLACK", label: "Black", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },
  { id: "COLOR_WHITE", label: "White", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },
  { id: "COLOR_GRAY", label: "Gray", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.COLOR, pack: "BASE_GAME" },

  // Music Genres
  { id: "MUSIC_ALTERNATIVE", label: "Alternative", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_AMERICANA", label: "Americana", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "HORSE_RANCH" },
  { id: "MUSIC_BLUES", label: "Blues", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_CLASSICAL", label: "Classical", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_EASY_LISTENING", label: "Easy Listening", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_ELECTRONICA", label: "Electronica", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_FOCUS", label: "Focus", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "DISCOVER_UNIVERSITY" },
  { id: "MUSIC_GOSPEL", label: "Gospel", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_HIPHOP", label: "Hip Hop", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "CITY_LIVING" },
  { id: "MUSIC_INDIE", label: "Indie", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_ISLAND", label: "Island", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "ISLAND_LIVING" },
  { id: "MUSIC_JAPANESE_FOLK", label: "Japanese Folk", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "SNOWY_ESCAPE" },
  { id: "MUSIC_JAZZ", label: "Jazz", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_LATIN", label: "Latin", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_LULLABIES", label: "Lullabies Radio", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "TODDLER_STUFF" },
  { id: "MUSIC_METAL", label: "Metal", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_NEWDISCO", label: "NuDisco", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "GET_TOGETHER" },
  { id: "MUSIC_POLYNESIAN", label: "Polynesian", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "ISLAND_LIVING" },
  { id: "MUSIC_POP", label: "Pop", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_RANCH", label: "Ranch", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "HORSE_RANCH" },
  { id: "MUSIC_RETRO", label: "Retro", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_ROMANCE", label: "Romance", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_SPOP", label: "S-Pop", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "CITY_LIVING" },
  { id: "MUSIC_SINGER_SONGWRITER", label: "Singer-Songwriter", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "ECO_LIFESTYLE" },
  { id: "MUSIC_SOUL", label: "Soul", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_WINTER_HOLIDAY", label: "Winter Holiday", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_WORLD", label: "World", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "BASE_GAME" },
  { id: "MUSIC_DRILL", label: "Drill", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.MUSIC, pack: "HIGH_SCHOOL_YEARS" },

  // Activities
  { id: "ACTIVITY_ACTING", label: "Acting", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "GET_FAMOUS" },
  { id: "ACTIVITY_BAKING", label: "Baking", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_BOWLING", label: "Bowling", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BOWLING_NIGHT" },
  { id: "ACTIVITY_COMEDY", label: "Comedy", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_COOKING", label: "Cooking", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_CROSS_STITCH", label: "Cross-Stitch", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "COTTAGE_LIVING" },
  { id: "ACTIVITY_DANCING", label: "Dancing", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "GET_TOGETHER" },
  { id: "ACTIVITY_DJ_MIXING", label: "DJ Mixing", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "GET_TOGETHER" },
  { id: "ACTIVITY_FABRICATION", label: "Fabrication", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "ECO_LIFESTYLE" },
  { id: "ACTIVITY_FISHING", label: "Fishing", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_FITNESS", label: "Fitness", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_FLOWER_ARRANGING", label: "Flower Arranging", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "SEASONS" },
  { id: "ACTIVITY_GARDENING", label: "Gardening", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_GUITAR", label: "Guitar", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_HANDINESS", label: "Handiness", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_HORSE_RIDING", label: "Horse Riding", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "HORSE_RANCH" },
  { id: "ACTIVITY_JUICE_FIZZING", label: "Juice Fizzing", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "ECO_LIFESTYLE" },
  { id: "ACTIVITY_KNITTING", label: "Knitting", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "NIFTY_KNITTING" },
  { id: "ACTIVITY_LOGIC", label: "Logic", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_MEDIA_PRODUCTION", label: "Media Production", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "GET_FAMOUS" },
  { id: "ACTIVITY_MISCHIEF", label: "Mischief", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_MIXOLOGY", label: "Mixology", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_PAINTING", label: "Painting", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_PARENTING", label: "Parenting", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "PARENTHOOD" },
  { id: "ACTIVITY_PHOTOGRAPHY", label: "Photography", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "GET_TO_WORK" },
  { id: "ACTIVITY_PIANO", label: "Piano", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_PROGRAMMING", label: "Programming", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_RESEARCH_DEBATE", label: "Research & Debate", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "DISCOVER_UNIVERSITY" },
  { id: "ACTIVITY_ROBOTICS", label: "Robotics", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "DISCOVER_UNIVERSITY" },
  { id: "ACTIVITY_ROCKET_SCIENCE", label: "Rocket Science", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_SINGING", label: "Singing", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "CITY_LIVING" },
  { id: "ACTIVITY_SKIING", label: "Skiing", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "SNOWY_ESCAPE" },
  { id: "ACTIVITY_SNOWBOARDING", label: "Snowboarding", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "SNOWY_ESCAPE" },
  { id: "ACTIVITY_ROCK_CLIMBING", label: "Rock Climbing", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "SNOWY_ESCAPE" },
  { id: "ACTIVITY_VIDEO_GAMING", label: "Video Gaming", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_VIOLIN", label: "Violin", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },
  { id: "ACTIVITY_WELLNESS", label: "Wellness", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "SPA_DAY" },
  { id: "ACTIVITY_WRITING", label: "Writing", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.ACTIVITY, pack: "BASE_GAME" },

  // Décor (all Base Game unless noted)
  { id: "DECOR_ART_DECO", label: "Art Deco", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_BASIC", label: "Basic", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_BOHO", label: "Boho", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_CONTEMPORARY", label: "Contemporary", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_COSMOLUX", label: "Cosmolux", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_CRAFTSMAN", label: "Craftsman", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_FRENCH_COUNTRY", label: "French Country", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_GARDEN", label: "Garden", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_GOTHIC_FARMHOUSE", label: "Gothic Farmhouse", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_INDUSTRIAL", label: "Industrial", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_ISLAND", label: "Island", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "ISLAND_LIVING" },
  { id: "DECOR_MID_CENTURY", label: "Mid-Century", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_MISSION", label: "Mission", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_MODERN", label: "Modern", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_OLD_MONEY", label: "Old Money", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_PATIO", label: "Patio", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_POLISHED", label: "Polished", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_QUEEN_ANNE", label: "Queen Anne", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_SCANDI", label: "Scandi", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_SHABBY", label: "Shabby", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_STORYBOOK", label: "Storybook", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_SUBURBAN_CONTEMPO", label: "Suburban Contempo", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_TRADITIONAL", label: "Traditional", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_VINTAGE", label: "Vintage", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },
  { id: "DECOR_LUXE", label: "Luxe", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.DECOR, pack: "BASE_GAME" },

  // Sim Characteristics (Base Game)
  { id: "SIMCHAR_AMBITIOUS", label: "Ambitious Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_BRO", label: "Bro Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_CAT_LOVER", label: "Cat Lovers", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "CATS_AND_DOGS" },
  { id: "SIMCHAR_CHEERFUL", label: "Cheerful Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_CHILDISH", label: "Childish Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_CLUMSY", label: "Clumsy Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_CREATIVE", label: "Creative Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_DOG_LOVER", label: "Dog Lovers", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "CATS_AND_DOGS" },
  { id: "SIMCHAR_FAMILY_ORIENTED", label: "Family-Oriented Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_FOODIE", label: "Foodie Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_GEEK", label: "Geek Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_GENIUS", label: "Genius Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_GOOFBALL", label: "Goofball Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_HIGH_ENERGY", label: "High Energy Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_HOMEBODY", label: "Homebody Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_JOKESTERS", label: "Jokesters", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_LACTOSE_INTOLERANT", label: "Lactose Intolerant Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "COTTAGE_LIVING" },
  { id: "SIMCHAR_LAZY", label: "Lazy Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_OUTDOORSY", label: "Outdoorsy Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_PERFECTIONIST", label: "Perfectionist Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_ROMANTIC", label: "Romantic Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_SINCERE", label: "Sincere Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_SPONTANEOUS", label: "Spontaneous Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },
  { id: "SIMCHAR_SPIRITED", label: "Spirited Sims", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.SIM_CHARACTERISTIC, pack: "BASE_GAME" },

  // Conversation Topics (Base Game)
  { id: "CONVO_DEEP_THOUGHTS", label: "Deep Thoughts", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" },
  { id: "CONVO_INTERESTS", label: "Discussions about Interests", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" },
  { id: "CONVO_SMALL_TALK", label: "Small Talk", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" },
  { id: "CONVO_JOKES", label: "Jokes", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" },
  { id: "CONVO_GOSSIP", label: "Gossip", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" },
  { id: "CONVO_COMPLAINTS", label: "Complaints", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" },
  { id: "CONVO_SILLY_BEHAVIOR", label: "Silly Behavior", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" },
  { id: "CONVO_PRANKS", label: "Pranks", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" },
  { id: "CONVO_ARGUMENTS", label: "Arguments", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" },
  { id: "CONVO_FLIRTING", label: "Flirting", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" },
  { id: "CONVO_PHYSICAL_INTIMACY", label: "Physical Intimacy", achievementType: AchievementType.PREFERENCE, preferenceType: PreferenceType.CONVERSATION_TOPIC, pack: "BASE_GAME" }
];